serverAddr = "20.6.33.77"
serverPort = 7000
auth.token = ""

webServer.addr = "0.0.0.0"
webServer.port = 7400
webServer.user = "admin"
webServer.password = "admin"

[[proxies]]
name = "adb"
type = "tcp"
localIP = "127.0.0.1"
localPort = 5555
remotePort = 5555
